obj-$(CONFIG_MACH_APQ8064_VEGA) += board-vega.o \
	board-vega-camera.o \
	board-vega-display.o \
	board-vega-gpiomux.o \
	board-vega-gpu.o \
	board-vega-pmic.o \
	board-vega-regulator.o \
	board-vega-storage.o  \
	board-vega-input.o \
	board-vega-sound.o

CFLAGS_board-vega-display.o += -Idrivers/video
CFLAGS_board-vega.o += -Idrivers/staging/android
